// Comprehensive dataset of all 193 UN countries with real rankings
export interface CountryData {
  name: string
  code: string
  flag: string
  rankings: {
    Population: number
    FIFA: number
    Size: number
    Crime: number
    GDP: number
    Tourism: number
    Gas: number
    Coffee: number
  }
}

export const countries: CountryData[] = [
  {
    name: "China",
    code: "cn",
    flag: "https://flagpedia.net/data/flags/w80/cn.png",
    rankings: { Population: 2, FIFA: 79, Size: 4, Crime: 142, GDP: 2, Tourism: 4, Gas: 6, Coffee: 19 },
  },
  {
    name: "India",
    code: "in",
    flag: "https://flagpedia.net/data/flags/w80/in.png",
    rankings: { Population: 1, FIFA: 106, Size: 7, Crime: 44, GDP: 5, Tourism: 22, Gas: 3, Coffee: 6 },
  },
  {
    name: "United States",
    code: "us",
    flag: "https://flagpedia.net/data/flags/w80/us.png",
    rankings: { Population: 3, FIFA: 11, Size: 3, Crime: 56, GDP: 1, Tourism: 2, Gas: 1, Coffee: 26 },
  },
  {
    name: "Indonesia",
    code: "id",
    flag: "https://flagpedia.net/data/flags/w80/id.png",
    rankings: { Population: 4, FIFA: 134, Size: 15, Crime: 64, GDP: 16, Tourism: 16, Gas: 8, Coffee: 4 },
  },
  {
    name: "Pakistan",
    code: "pk",
    flag: "https://flagpedia.net/data/flags/w80/pk.png",
    rankings: { Population: 5, FIFA: 195, Size: 34, Crime: 153, GDP: 24, Tourism: 75, Gas: 26, Coffee: 67 },
  },
  {
    name: "Brazil",
    code: "br",
    flag: "https://flagpedia.net/data/flags/w80/br.png",
    rankings: { Population: 6, FIFA: 4, Size: 5, Crime: 116, GDP: 12, Tourism: 37, Gas: 15, Coffee: 1 },
  },
  {
    name: "Nigeria",
    code: "ng",
    flag: "https://flagpedia.net/data/flags/w80/ng.png",
    rankings: { Population: 7, FIFA: 44, Size: 32, Crime: 146, GDP: 31, Tourism: 67, Gas: 9, Coffee: 45 },
  },
  {
    name: "Bangladesh",
    code: "bd",
    flag: "https://flagpedia.net/data/flags/w80/bd.png",
    rankings: { Population: 8, FIFA: 184, Size: 94, Crime: 68, GDP: 35, Tourism: 99, Gas: 58, Coffee: 89 },
  },
  {
    name: "Russia",
    code: "ru",
    flag: "https://flagpedia.net/data/flags/w80/ru.png",
    rankings: { Population: 9, FIFA: 34, Size: 1, Crime: 102, GDP: 11, Tourism: 39, Gas: 2, Coffee: 78 },
  },
  {
    name: "Mexico",
    code: "mx",
    flag: "https://flagpedia.net/data/flags/w80/mx.png",
    rankings: { Population: 10, FIFA: 17, Size: 14, Crime: 140, GDP: 15, Tourism: 6, Gas: 12, Coffee: 11 },
  },
  {
    name: "Japan",
    code: "jp",
    flag: "https://flagpedia.net/data/flags/w80/jp.png",
    rankings: { Population: 11, FIFA: 20, Size: 62, Crime: 25, GDP: 4, Tourism: 11, Gas: 37, Coffee: 42 },
  },
  {
    name: "Ethiopia",
    code: "et",
    flag: "https://flagpedia.net/data/flags/w80/et.png",
    rankings: { Population: 12, FIFA: 150, Size: 27, Crime: 74, GDP: 59, Tourism: 52, Gas: 167, Coffee: 5 },
  },
  {
    name: "Philippines",
    code: "ph",
    flag: "https://flagpedia.net/data/flags/w80/ph.png",
    rankings: { Population: 13, FIFA: 135, Size: 73, Crime: 113, GDP: 32, Tourism: 19, Gas: 43, Coffee: 18 },
  },
  {
    name: "Egypt",
    code: "eg",
    flag: "https://flagpedia.net/data/flags/w80/eg.png",
    rankings: { Population: 14, FIFA: 33, Size: 30, Crime: 118, GDP: 34, Tourism: 30, Gas: 16, Coffee: 156 },
  },
  {
    name: "Vietnam",
    code: "vn",
    flag: "https://flagpedia.net/data/flags/w80/vn.png",
    rankings: { Population: 15, FIFA: 116, Size: 66, Crime: 57, GDP: 25, Tourism: 8, Gas: 52, Coffee: 2 },
  },
  {
    name: "Turkey",
    code: "tr",
    flag: "https://flagpedia.net/data/flags/w80/tr.png",
    rankings: { Population: 16, FIFA: 42, Size: 37, Crime: 93, GDP: 19, Tourism: 4, Gas: 38, Coffee: 35 },
  },
  {
    name: "Iran",
    code: "ir",
    flag: "https://flagpedia.net/data/flags/w80/ir.png",
    rankings: { Population: 17, FIFA: 21, Size: 18, Crime: 103, GDP: 17, Tourism: 68, Gas: 4, Coffee: 134 },
  },
  {
    name: "Germany",
    code: "de",
    flag: "https://flagpedia.net/data/flags/w80/de.png",
    rankings: { Population: 19, FIFA: 16, Size: 63, Crime: 18, GDP: 4, Tourism: 9, Gas: 27, Coffee: 17 },
  },
  {
    name: "Thailand",
    code: "th",
    flag: "https://flagpedia.net/data/flags/w80/th.png",
    rankings: { Population: 20, FIFA: 96, Size: 51, Crime: 118, GDP: 26, Tourism: 10, Gas: 46, Coffee: 23 },
  },
  {
    name: "United Kingdom",
    code: "gb",
    flag: "https://flagpedia.net/data/flags/w80/gb.png",
    rankings: { Population: 21, FIFA: 5, Size: 80, Crime: 33, GDP: 6, Tourism: 7, Gas: 21, Coffee: 38 },
  },
  {
    name: "France",
    code: "fr",
    flag: "https://flagpedia.net/data/flags/w80/fr.png",
    rankings: { Population: 22, FIFA: 2, Size: 49, Crime: 51, GDP: 7, Tourism: 1, Gas: 43, Coffee: 45 },
  },
  {
    name: "Italy",
    code: "it",
    flag: "https://flagpedia.net/data/flags/w80/it.png",
    rankings: { Population: 23, FIFA: 9, Size: 72, Crime: 47, GDP: 8, Tourism: 5, Gas: 36, Coffee: 7 },
  },
  {
    name: "Tanzania",
    code: "tz",
    flag: "https://flagpedia.net/data/flags/w80/tz.png",
    rankings: { Population: 24, FIFA: 125, Size: 13, Crime: 85, GDP: 75, Tourism: 46, Gas: 78, Coffee: 24 },
  },
  {
    name: "South Africa",
    code: "za",
    flag: "https://flagpedia.net/data/flags/w80/za.png",
    rankings: { Population: 25, FIFA: 57, Size: 25, Crime: 137, GDP: 33, Tourism: 36, Gas: 39, Coffee: 87 },
  },
  {
    name: "Myanmar",
    code: "mm",
    flag: "https://flagpedia.net/data/flags/w80/mm.png",
    rankings: { Population: 26, FIFA: 180, Size: 40, Crime: 106, GDP: 71, Tourism: 65, Gas: 23, Coffee: 125 },
  },
  {
    name: "Kenya",
    code: "ke",
    flag: "https://flagpedia.net/data/flags/w80/ke.png",
    rankings: { Population: 27, FIFA: 109, Size: 48, Crime: 130, GDP: 63, Tourism: 48, Gas: 145, Coffee: 16 },
  },
  {
    name: "South Korea",
    code: "kr",
    flag: "https://flagpedia.net/data/flags/w80/kr.png",
    rankings: { Population: 28, FIFA: 23, Size: 109, Crime: 35, GDP: 10, Tourism: 20, Gas: 45, Coffee: 29 },
  },
  {
    name: "Colombia",
    code: "co",
    flag: "https://flagpedia.net/data/flags/w80/co.png",
    rankings: { Population: 29, FIFA: 12, Size: 26, Crime: 144, GDP: 39, Tourism: 47, Gas: 28, Coffee: 3 },
  },
  {
    name: "Spain",
    code: "es",
    flag: "https://flagpedia.net/data/flags/w80/es.png",
    rankings: { Population: 30, FIFA: 8, Size: 52, Crime: 32, GDP: 14, Tourism: 2, Gas: 34, Coffee: 31 },
  },
  {
    name: "Uganda",
    code: "ug",
    flag: "https://flagpedia.net/data/flags/w80/ug.png",
    rankings: { Population: 31, FIFA: 90, Size: 81, Crime: 121, GDP: 91, Tourism: 84, Gas: 178, Coffee: 8 },
  },
  {
    name: "Argentina",
    code: "ar",
    flag: "https://flagpedia.net/data/flags/w80/ar.png",
    rankings: { Population: 32, FIFA: 1, Size: 8, Crime: 82, GDP: 22, Tourism: 50, Gas: 31, Coffee: 85 },
  },
  {
    name: "Algeria",
    code: "dz",
    flag: "https://flagpedia.net/data/flags/w80/dz.png",
    rankings: { Population: 33, FIFA: 37, Size: 10, Crime: 91, GDP: 53, Tourism: 90, Gas: 10, Coffee: 172 },
  },
  {
    name: "Sudan",
    code: "sd",
    flag: "https://flagpedia.net/data/flags/w80/sd.png",
    rankings: { Population: 34, FIFA: 125, Size: 16, Crime: 167, GDP: 85, Tourism: 174, Gas: 87, Coffee: 145 },
  },
  {
    name: "Ukraine",
    code: "ua",
    flag: "https://flagpedia.net/data/flags/w80/ua.png",
    rankings: { Population: 35, FIFA: 27, Size: 46, Crime: 78, GDP: 57, Tourism: 88, Gas: 26, Coffee: 112 },
  },
  {
    name: "Iraq",
    code: "iq",
    flag: "https://flagpedia.net/data/flags/w80/iq.png",
    rankings: { Population: 36, FIFA: 70, Size: 58, Crime: 165, GDP: 50, Tourism: 121, Gas: 5, Coffee: 189 },
  },
  {
    name: "Afghanistan",
    code: "af",
    flag: "https://flagpedia.net/data/flags/w80/af.png",
    rankings: { Population: 37, FIFA: 150, Size: 41, Crime: 163, GDP: 96, Tourism: 184, Gas: 56, Coffee: 178 },
  },
  {
    name: "Poland",
    code: "pl",
    flag: "https://flagpedia.net/data/flags/w80/pl.png",
    rankings: { Population: 38, FIFA: 31, Size: 70, Crime: 23, GDP: 21, Tourism: 17, Gas: 35, Coffee: 41 },
  },
  {
    name: "Canada",
    code: "ca",
    flag: "https://flagpedia.net/data/flags/w80/ca.png",
    rankings: { Population: 39, FIFA: 41, Size: 2, Crime: 14, GDP: 11, Tourism: 13, Gas: 4, Coffee: 24 },
  },
  {
    name: "Morocco",
    code: "ma",
    flag: "https://flagpedia.net/data/flags/w80/ma.png",
    rankings: { Population: 40, FIFA: 14, Size: 57, Crime: 54, GDP: 61, Tourism: 11, Gas: 51, Coffee: 164 },
  },
  {
    name: "Saudi Arabia",
    code: "sa",
    flag: "https://flagpedia.net/data/flags/w80/sa.png",
    rankings: { Population: 41, FIFA: 56, Size: 12, Crime: 129, GDP: 18, Tourism: 33, Gas: 7, Coffee: 49 },
  },
  {
    name: "Uzbekistan",
    code: "uz",
    flag: "https://flagpedia.net/data/flags/w80/uz.png",
    rankings: { Population: 42, FIFA: 68, Size: 56, Crime: 45, GDP: 73, Tourism: 79, Gas: 14, Coffee: 183 },
  },
  {
    name: "Peru",
    code: "pe",
    flag: "https://flagpedia.net/data/flags/w80/pe.png",
    rankings: { Population: 43, FIFA: 36, Size: 19, Crime: 123, GDP: 47, Tourism: 28, Gas: 44, Coffee: 9 },
  },
  {
    name: "Angola",
    code: "ao",
    flag: "https://flagpedia.net/data/flags/w80/ao.png",
    rankings: { Population: 44, FIFA: 120, Size: 23, Crime: 156, GDP: 64, Tourism: 144, Gas: 17, Coffee: 77 },
  },
  {
    name: "Malaysia",
    code: "my",
    flag: "https://flagpedia.net/data/flags/w80/my.png",
    rankings: { Population: 45, FIFA: 135, Size: 67, Crime: 61, GDP: 36, Tourism: 26, Gas: 29, Coffee: 86 },
  },
  {
    name: "Mozambique",
    code: "mz",
    flag: "https://flagpedia.net/data/flags/w80/mz.png",
    rankings: { Population: 46, FIFA: 115, Size: 35, Crime: 134, GDP: 119, Tourism: 128, Gas: 11, Coffee: 158 },
  },
  {
    name: "Ghana",
    code: "gh",
    flag: "https://flagpedia.net/data/flags/w80/gh.png",
    rankings: { Population: 47, FIFA: 67, Size: 82, Crime: 73, GDP: 72, Tourism: 45, Gas: 48, Coffee: 22 },
  },
  {
    name: "Yemen",
    code: "ye",
    flag: "https://flagpedia.net/data/flags/w80/ye.png",
    rankings: { Population: 48, FIFA: 154, Size: 50, Crime: 179, GDP: 117, Tourism: 183, Gas: 33, Coffee: 25 },
  },
  {
    name: "Nepal",
    code: "np",
    flag: "https://flagpedia.net/data/flags/w80/np.png",
    rankings: { Population: 49, FIFA: 172, Size: 93, Crime: 76, GDP: 103, Tourism: 40, Gas: 162, Coffee: 139 },
  },
  {
    name: "Venezuela",
    code: "ve",
    flag: "https://flagpedia.net/data/flags/w80/ve.png",
    rankings: { Population: 50, FIFA: 54, Size: 33, Crime: 176, GDP: 76, Tourism: 78, Gas: 8, Coffee: 20 },
  },
  {
    name: "Madagascar",
    code: "mg",
    flag: "https://flagpedia.net/data/flags/w80/mg.png",
    rankings: { Population: 51, FIFA: 108, Size: 47, Crime: 72, GDP: 134, Tourism: 87, Gas: 184, Coffee: 21 },
  },
  {
    name: "Cameroon",
    code: "cm",
    flag: "https://flagpedia.net/data/flags/w80/cm.png",
    rankings: { Population: 52, FIFA: 51, Size: 54, Crime: 135, GDP: 89, Tourism: 66, Gas: 40, Coffee: 27 },
  },
  {
    name: "Côte d'Ivoire",
    code: "ci",
    flag: "https://flagpedia.net/data/flags/w80/ci.png",
    rankings: { Population: 53, FIFA: 58, Size: 69, Crime: 110, GDP: 78, Tourism: 85, Gas: 47, Coffee: 12 },
  },
  {
    name: "North Korea",
    code: "kp",
    flag: "https://flagpedia.net/data/flags/w80/kp.png",
    rankings: { Population: 54, FIFA: 111, Size: 99, Crime: 193, GDP: 115, Tourism: 193, Gas: 95, Coffee: 193 },
  },
  {
    name: "Australia",
    code: "au",
    flag: "https://flagpedia.net/data/flags/w80/au.png",
    rankings: { Population: 55, FIFA: 24, Size: 6, Crime: 13, GDP: 13, Tourism: 43, Gas: 19, Coffee: 48 },
  },
  {
    name: "Niger",
    code: "ne",
    flag: "https://flagpedia.net/data/flags/w80/ne.png",
    rankings: { Population: 56, FIFA: 125, Size: 22, Crime: 86, GDP: 124, Tourism: 156, Gas: 183, Coffee: 181 },
  },
  {
    name: "Taiwan",
    code: "tw",
    flag: "https://flagpedia.net/data/flags/w80/tw.png",
    rankings: { Population: 57, FIFA: 152, Size: 137, Crime: 26, GDP: 22, Tourism: 37, Gas: 67, Coffee: 33 },
  },
  {
    name: "Sri Lanka",
    code: "lk",
    flag: "https://flagpedia.net/data/flags/w80/lk.png",
    rankings: { Population: 58, FIFA: 207, Size: 130, Crime: 34, GDP: 65, Tourism: 64, Gas: 156, Coffee: 28 },
  },
  {
    name: "Burkina Faso",
    code: "bf",
    flag: "https://flagpedia.net/data/flags/w80/bf.png",
    rankings: { Population: 59, FIFA: 61, Size: 75, Crime: 97, GDP: 125, Tourism: 134, Gas: 185, Coffee: 175 },
  },
  {
    name: "Mali",
    code: "ml",
    flag: "https://flagpedia.net/data/flags/w80/ml.png",
    rankings: { Population: 60, FIFA: 128, Size: 24, Crime: 152, GDP: 118, Tourism: 139, Gas: 186, Coffee: 176 },
  },
  {
    name: "Romania",
    code: "ro",
    flag: "https://flagpedia.net/data/flags/w80/ro.png",
    rankings: { Population: 61, FIFA: 47, Size: 83, Crime: 25, GDP: 41, Tourism: 20, Gas: 30, Coffee: 56 },
  },
  {
    name: "Malawi",
    code: "mw",
    flag: "https://flagpedia.net/data/flags/w80/mw.png",
    rankings: { Population: 62, FIFA: 115, Size: 100, Crime: 96, GDP: 145, Tourism: 140, Gas: 187, Coffee: 155 },
  },
  {
    name: "Chile",
    code: "cl",
    flag: "https://flagpedia.net/data/flags/w80/cl.png",
    rankings: { Population: 63, FIFA: 30, Size: 38, Crime: 50, GDP: 43, Tourism: 51, Gas: 41, Coffee: 84 },
  },
  {
    name: "Kazakhstan",
    code: "kz",
    flag: "https://flagpedia.net/data/flags/w80/kz.png",
    rankings: { Population: 64, FIFA: 122, Size: 9, Crime: 70, GDP: 55, Tourism: 80, Gas: 13, Coffee: 168 },
  },
  {
    name: "Zambia",
    code: "zm",
    flag: "https://flagpedia.net/data/flags/w80/zm.png",
    rankings: { Population: 65, FIFA: 88, Size: 39, Crime: 105, GDP: 106, Tourism: 104, Gas: 188, Coffee: 174 },
  },
  {
    name: "Guatemala",
    code: "gt",
    flag: "https://flagpedia.net/data/flags/w80/gt.png",
    rankings: { Population: 66, FIFA: 101, Size: 107, Crime: 171, GDP: 68, Tourism: 41, Gas: 149, Coffee: 10 },
  },
  {
    name: "Ecuador",
    code: "ec",
    flag: "https://flagpedia.net/data/flags/w80/ec.png",
    rankings: { Population: 67, FIFA: 25, Size: 74, Crime: 141, GDP: 61, Tourism: 54, Gas: 32, Coffee: 61 },
  },
  {
    name: "Syria",
    code: "sy",
    flag: "https://flagpedia.net/data/flags/w80/sy.png",
    rankings: { Population: 68, FIFA: 91, Size: 89, Crime: 161, GDP: 86, Tourism: 180, Gas: 42, Coffee: 190 },
  },
  {
    name: "Netherlands",
    code: "nl",
    flag: "https://flagpedia.net/data/flags/w80/nl.png",
    rankings: { Population: 69, FIFA: 7, Size: 131, Crime: 16, GDP: 18, Tourism: 21, Gas: 25, Coffee: 15 },
  },
  {
    name: "Senegal",
    code: "sn",
    flag: "https://flagpedia.net/data/flags/w80/sn.png",
    rankings: { Population: 70, FIFA: 20, Size: 88, Crime: 71, GDP: 110, Tourism: 85, Gas: 189, Coffee: 179 },
  },
  {
    name: "Cambodia",
    code: "kh",
    flag: "https://flagpedia.net/data/flags/w80/kh.png",
    rankings: { Population: 71, FIFA: 177, Size: 90, Crime: 92, GDP: 108, Tourism: 61, Gas: 190, Coffee: 157 },
  },
  {
    name: "Chad",
    code: "td",
    flag: "https://flagpedia.net/data/flags/w80/td.png",
    rankings: { Population: 72, FIFA: 184, Size: 20, Crime: 160, GDP: 126, Tourism: 175, Gas: 191, Coffee: 192 },
  },
  {
    name: "Somalia",
    code: "so",
    flag: "https://flagpedia.net/data/flags/w80/so.png",
    rankings: { Population: 73, FIFA: 139, Size: 43, Crime: 189, GDP: 158, Tourism: 191, Gas: 192, Coffee: 188 },
  },
  {
    name: "Zimbabwe",
    code: "zw",
    flag: "https://flagpedia.net/data/flags/w80/zw.png",
    rankings: { Population: 74, FIFA: 124, Size: 61, Crime: 115, GDP: 117, Tourism: 116, Gas: 193, Coffee: 173 },
  },
  {
    name: "Guinea",
    code: "gn",
    flag: "https://flagpedia.net/data/flags/w80/gn.png",
    rankings: { Population: 75, FIFA: 77, Size: 79, Crime: 114, GDP: 113, Tourism: 154, Gas: 194, Coffee: 14 },
  },
  {
    name: "Rwanda",
    code: "rw",
    flag: "https://flagpedia.net/data/flags/w80/rw.png",
    rankings: { Population: 76, FIFA: 140, Size: 149, Crime: 38, GDP: 124, Tourism: 99, Gas: 195, Coffee: 30 },
  },
  {
    name: "Benin",
    code: "bj",
    flag: "https://flagpedia.net/data/flags/w80/bj.png",
    rankings: { Population: 77, FIFA: 93, Size: 103, Crime: 84, GDP: 135, Tourism: 160, Gas: 196, Coffee: 180 },
  },
  {
    name: "Burundi",
    code: "bi",
    flag: "https://flagpedia.net/data/flags/w80/bi.png",
    rankings: { Population: 78, FIFA: 138, Size: 146, Crime: 104, GDP: 185, Tourism: 181, Gas: 197, Coffee: 13 },
  },
  {
    name: "Tunisia",
    code: "tn",
    flag: "https://flagpedia.net/data/flags/w80/tn.png",
    rankings: { Population: 79, FIFA: 47, Size: 92, Crime: 77, GDP: 75, Tourism: 29, Gas: 49, Coffee: 165 },
  },
  {
    name: "Bolivia",
    code: "bo",
    flag: "https://flagpedia.net/data/flags/w80/bo.png",
    rankings: { Population: 80, FIFA: 84, Size: 28, Crime: 108, GDP: 95, Tourism: 57, Gas: 50, Coffee: 34 },
  },
  {
    name: "Belgium",
    code: "be",
    flag: "https://flagpedia.net/data/flags/w80/be.png",
    rankings: { Population: 81, FIFA: 3, Size: 140, Crime: 21, GDP: 23, Tourism: 14, Gas: 54, Coffee: 37 },
  },
  {
    name: "Haiti",
    code: "ht",
    flag: "https://flagpedia.net/data/flags/w80/ht.png",
    rankings: { Population: 82, FIFA: 101, Size: 148, Crime: 174, GDP: 149, Tourism: 83, Gas: 198, Coffee: 32 },
  },
  {
    name: "Cuba",
    code: "cu",
    flag: "https://flagpedia.net/data/flags/w80/cu.png",
    rankings: { Population: 83, FIFA: 173, Size: 105, Crime: 42, GDP: 78, Tourism: 59, Gas: 55, Coffee: 46 },
  },
  {
    name: "South Sudan",
    code: "ss",
    flag: "https://flagpedia.net/data/flags/w80/ss.png",
    rankings: { Population: 84, FIFA: 169, Size: 42, Crime: 187, GDP: 175, Tourism: 192, Gas: 199, Coffee: 191 },
  },
  {
    name: "Dominican Republic",
    code: "do",
    flag: "https://flagpedia.net/data/flags/w80/do.png",
    rankings: { Population: 85, FIFA: 76, Size: 129, Crime: 132, GDP: 69, Tourism: 23, Gas: 153, Coffee: 36 },
  },
  {
    name: "Czech Republic",
    code: "cz",
    flag: "https://flagpedia.net/data/flags/w80/cz.png",
    rankings: { Population: 86, FIFA: 18, Size: 115, Crime: 24, GDP: 37, Tourism: 18, Gas: 57, Coffee: 39 },
  },
  {
    name: "Greece",
    code: "gr",
    flag: "https://flagpedia.net/data/flags/w80/gr.png",
    rankings: { Population: 87, FIFA: 48, Size: 96, Crime: 31, GDP: 51, Tourism: 15, Gas: 59, Coffee: 40 },
  },
  {
    name: "Jordan",
    code: "jo",
    flag: "https://flagpedia.net/data/flags/w80/jo.png",
    rankings: { Population: 88, FIFA: 87, Size: 112, Crime: 60, GDP: 89, Tourism: 49, Gas: 60, Coffee: 166 },
  },
  {
    name: "Portugal",
    code: "pt",
    flag: "https://flagpedia.net/data/flags/w80/pt.png",
    rankings: { Population: 89, FIFA: 6, Size: 111, Crime: 11, GDP: 46, Tourism: 12, Gas: 61, Coffee: 43 },
  },
  {
    name: "Azerbaijan",
    code: "az",
    flag: "https://flagpedia.net/data/flags/w80/az.png",
    rankings: { Population: 90, FIFA: 71, Size: 113, Crime: 58, GDP: 87, Tourism: 89, Gas: 18, Coffee: 169 },
  },
  {
    name: "Sweden",
    code: "se",
    flag: "https://flagpedia.net/data/flags/w80/se.png",
    rankings: { Population: 91, FIFA: 19, Size: 55, Crime: 4, GDP: 23, Tourism: 25, Gas: 62, Coffee: 6 },
  },
  {
    name: "Honduras",
    code: "hn",
    flag: "https://flagpedia.net/data/flags/w80/hn.png",
    rankings: { Population: 92, FIFA: 78, Size: 102, Crime: 172, GDP: 101, Tourism: 73, Gas: 154, Coffee: 47 },
  },
  {
    name: "United Arab Emirates",
    code: "ae",
    flag: "https://flagpedia.net/data/flags/w80/ae.png",
    rankings: { Population: 93, FIFA: 69, Size: 114, Crime: 17, GDP: 31, Tourism: 24, Gas: 20, Coffee: 50 },
  },
  {
    name: "Hungary",
    code: "hu",
    flag: "https://flagpedia.net/data/flags/w80/hu.png",
    rankings: { Population: 94, FIFA: 26, Size: 109, Crime: 19, GDP: 53, Tourism: 35, Gas: 63, Coffee: 44 },
  },
  {
    name: "Tajikistan",
    code: "tj",
    flag: "https://flagpedia.net/data/flags/w80/tj.png",
    rankings: { Population: 95, FIFA: 106, Size: 95, Crime: 52, GDP: 144, Tourism: 125, Gas: 64, Coffee: 182 },
  },
  {
    name: "Belarus",
    code: "by",
    flag: "https://flagpedia.net/data/flags/w80/by.png",
    rankings: { Population: 96, FIFA: 90, Size: 84, Crime: 36, GDP: 60, Tourism: 86, Gas: 65, Coffee: 170 },
  },
  {
    name: "Austria",
    code: "at",
    flag: "https://flagpedia.net/data/flags/w80/at.png",
    rankings: { Population: 97, FIFA: 23, Size: 113, Crime: 9, GDP: 27, Tourism: 16, Gas: 66, Coffee: 51 },
  },
  {
    name: "Papua New Guinea",
    code: "pg",
    flag: "https://flagpedia.net/data/flags/w80/pg.png",
    rankings: { Population: 98, FIFA: 165, Size: 54, Crime: 133, GDP: 120, Tourism: 130, Gas: 68, Coffee: 19 },
  },
  {
    name: "Serbia",
    code: "rs",
    flag: "https://flagpedia.net/data/flags/w80/rs.png",
    rankings: { Population: 99, FIFA: 32, Size: 87, Crime: 48, GDP: 52, Tourism: 95, Gas: 69, Coffee: 52 },
  },
  {
    name: "Israel",
    code: "il",
    flag: "https://flagpedia.net/data/flags/w80/il.png",
    rankings: { Population: 100, FIFA: 81, Size: 153, Crime: 29, GDP: 29, Tourism: 55, Gas: 70, Coffee: 53 },
  },
  {
    name: "Switzerland",
    code: "ch",
    flag: "https://flagpedia.net/data/flags/w80/ch.png",
    rankings: { Population: 101, FIFA: 15, Size: 135, Crime: 5, GDP: 20, Tourism: 19, Gas: 71, Coffee: 54 },
  },
  {
    name: "Togo",
    code: "tg",
    flag: "https://flagpedia.net/data/flags/w80/tg.png",
    rankings: { Population: 102, FIFA: 125, Size: 125, Crime: 87, GDP: 159, Tourism: 148, Gas: 72, Coffee: 55 },
  },
  {
    name: "Georgia",
    code: "ge",
    flag: "https://flagpedia.net/data/flags/w80/ge.png",
    rankings: { Population: 103, FIFA: 75, Size: 121, Crime: 37, GDP: 115, Tourism: 58, Gas: 73, Coffee: 171 },
  },
  {
    name: "Sierra Leone",
    code: "sl",
    flag: "https://flagpedia.net/data/flags/w80/sl.png",
    rankings: { Population: 104, FIFA: 108, Size: 118, Crime: 75, GDP: 161, Tourism: 155, Gas: 74, Coffee: 57 },
  },
  {
    name: "Laos",
    code: "la",
    flag: "https://flagpedia.net/data/flags/w80/la.png",
    rankings: { Population: 105, FIFA: 187, Size: 83, Crime: 56, GDP: 118, Tourism: 83, Gas: 75, Coffee: 58 },
  },
  {
    name: "Paraguay",
    code: "py",
    flag: "https://flagpedia.net/data/flags/w80/py.png",
    rankings: { Population: 106, FIFA: 62, Size: 60, Crime: 107, GDP: 90, Tourism: 105, Gas: 76, Coffee: 59 },
  },
  {
    name: "Bulgaria",
    code: "bg",
    flag: "https://flagpedia.net/data/flags/w80/bg.png",
    rankings: { Population: 107, FIFA: 74, Size: 104, Crime: 22, GDP: 67, Tourism: 42, Gas: 77, Coffee: 60 },
  },
  {
    name: "Libya",
    code: "ly",
    flag: "https://flagpedia.net/data/flags/w80/ly.png",
    rankings: { Population: 108, FIFA: 117, Size: 17, Crime: 168, GDP: 66, Tourism: 171, Gas: 22, Coffee: 187 },
  },
  {
    name: "Lebanon",
    code: "lb",
    flag: "https://flagpedia.net/data/flags/w80/lb.png",
    rankings: { Population: 109, FIFA: 117, Size: 166, Crime: 126, GDP: 81, Tourism: 56, Gas: 79, Coffee: 62 },
  },
  {
    name: "Nicaragua",
    code: "ni",
    flag: "https://flagpedia.net/data/flags/w80/ni.png",
    rankings: { Population: 110, FIFA: 151, Size: 98, Crime: 109, GDP: 128, Tourism: 74, Gas: 80, Coffee: 63 },
  },
  {
    name: "Kyrgyzstan",
    code: "kg",
    flag: "https://flagpedia.net/data/flags/w80/kg.png",
    rankings: { Population: 111, FIFA: 109, Size: 86, Crime: 46, GDP: 147, Tourism: 106, Gas: 81, Coffee: 184 },
  },
  {
    name: "El Salvador",
    code: "sv",
    flag: "https://flagpedia.net/data/flags/w80/sv.png",
    rankings: { Population: 112, FIFA: 66, Size: 154, Crime: 170, GDP: 104, Tourism: 91, Gas: 82, Coffee: 64 },
  },
  {
    name: "Turkmenistan",
    code: "tm",
    flag: "https://flagpedia.net/data/flags/w80/tm.png",
    rankings: { Population: 113, FIFA: 135, Size: 52, Crime: 59, GDP: 93, Tourism: 165, Gas: 24, Coffee: 185 },
  },
  {
    name: "Singapore",
    code: "sg",
    flag: "https://flagpedia.net/data/flags/w80/sg.png",
    rankings: { Population: 114, FIFA: 158, Size: 190, Crime: 2, GDP: 38, Tourism: 34, Gas: 83, Coffee: 65 },
  },
  {
    name: "Denmark",
    code: "dk",
    flag: "https://flagpedia.net/data/flags/w80/dk.png",
    rankings: { Population: 115, FIFA: 21, Size: 130, Crime: 6, GDP: 37, Tourism: 32, Gas: 84, Coffee: 66 },
  },
  {
    name: "Finland",
    code: "fi",
    flag: "https://flagpedia.net/data/flags/w80/fi.png",
    rankings: { Population: 116, FIFA: 59, Size: 64, Crime: 3, GDP: 48, Tourism: 60, Gas: 85, Coffee: 1 },
  },
  {
    name: "Congo",
    code: "cg",
    flag: "https://flagpedia.net/data/flags/w80/cg.png",
    rankings: { Population: 117, FIFA: 115, Size: 65, Crime: 148, GDP: 112, Tourism: 158, Gas: 86, Coffee: 68 },
  },
  {
    name: "Slovakia",
    code: "sk",
    flag: "https://flagpedia.net/data/flags/w80/sk.png",
    rankings: { Population: 118, FIFA: 48, Size: 127, Crime: 20, GDP: 58, Tourism: 77, Gas: 88, Coffee: 69 },
  },
  {
    name: "Norway",
    code: "no",
    flag: "https://flagpedia.net/data/flags/w80/no.png",
    rankings: { Population: 119, FIFA: 50, Size: 68, Crime: 7, GDP: 30, Tourism: 44, Gas: 15, Coffee: 70 },
  },
  {
    name: "Oman",
    code: "om",
    flag: "https://flagpedia.net/data/flags/w80/om.png",
    rankings: { Population: 120, FIFA: 73, Size: 71, Crime: 12, GDP: 62, Tourism: 69, Gas: 89, Coffee: 71 },
  },
  {
    name: "State of Palestine",
    code: "ps",
    flag: "https://flagpedia.net/data/flags/w80/ps.png",
    rankings: { Population: 121, FIFA: 100, Size: 167, Crime: 127, GDP: 130, Tourism: 124, Gas: 90, Coffee: 72 },
  },
  {
    name: "Costa Rica",
    code: "cr",
    flag: "https://flagpedia.net/data/flags/w80/cr.png",
    rankings: { Population: 122, FIFA: 52, Size: 128, Crime: 49, GDP: 80, Tourism: 38, Gas: 91, Coffee: 73 },
  },
  {
    name: "Liberia",
    code: "lr",
    flag: "https://flagpedia.net/data/flags/w80/lr.png",
    rankings: { Population: 123, FIFA: 142, Size: 103, Crime: 88, GDP: 167, Tourism: 162, Gas: 92, Coffee: 74 },
  },
  {
    name: "Ireland",
    code: "ie",
    flag: "https://flagpedia.net/data/flags/w80/ie.png",
    rankings: { Population: 124, FIFA: 60, Size: 120, Crime: 15, GDP: 25, Tourism: 27, Gas: 93, Coffee: 75 },
  },
  {
    name: "Central African Republic",
    code: "cf",
    flag: "https://flagpedia.net/data/flags/w80/cf.png",
    rankings: { Population: 125, FIFA: 125, Size: 45, Crime: 188, GDP: 188, Tourism: 188, Gas: 94, Coffee: 76 },
  },
  {
    name: "New Zealand",
    code: "nz",
    flag: "https://flagpedia.net/data/flags/w80/nz.png",
    rankings: { Population: 126, FIFA: 94, Size: 76, Crime: 1, GDP: 51, Tourism: 53, Gas: 96, Coffee: 79 },
  },
  {
    name: "Mauritania",
    code: "mr",
    flag: "https://flagpedia.net/data/flags/w80/mr.png",
    rankings: { Population: 127, FIFA: 103, Size: 29, Crime: 95, GDP: 140, Tourism: 167, Gas: 97, Coffee: 80 },
  },
  {
    name: "Panama",
    code: "pa",
    flag: "https://flagpedia.net/data/flags/w80/pa.png",
    rankings: { Population: 128, FIFA: 64, Size: 118, Crime: 111, GDP: 77, Tourism: 62, Gas: 98, Coffee: 81 },
  },
  {
    name: "Kuwait",
    code: "kw",
    flag: "https://flagpedia.net/data/flags/w80/kw.png",
    rankings: { Population: 129, FIFA: 137, Size: 157, Crime: 28, GDP: 56, Tourism: 92, Gas: 99, Coffee: 82 },
  },
  {
    name: "Croatia",
    code: "hr",
    flag: "https://flagpedia.net/data/flags/w80/hr.png",
    rankings: { Population: 130, FIFA: 10, Size: 126, Crime: 27, GDP: 56, Tourism: 31, Gas: 100, Coffee: 83 },
  },
  {
    name: "Moldova",
    code: "md",
    flag: "https://flagpedia.net/data/flags/w80/md.png",
    rankings: { Population: 131, FIFA: 181, Size: 139, Crime: 79, GDP: 138, Tourism: 145, Gas: 101, Coffee: 88 },
  },
  {
    name: "Georgia",
    code: "ge",
    flag: "https://flagpedia.net/data/flags/w80/ge.png",
    rankings: { Population: 132, FIFA: 75, Size: 121, Crime: 37, GDP: 115, Tourism: 58, Gas: 102, Coffee: 90 },
  },
  {
    name: "Eritrea",
    code: "er",
    flag: "https://flagpedia.net/data/flags/w80/er.png",
    rankings: { Population: 133, FIFA: 170, Size: 101, Crime: 155, GDP: 180, Tourism: 189, Gas: 103, Coffee: 91 },
  },
  {
    name: "Uruguay",
    code: "uy",
    flag: "https://flagpedia.net/data/flags/w80/uy.png",
    rankings: { Population: 134, FIFA: 13, Size: 91, Crime: 39, GDP: 54, Tourism: 63, Gas: 104, Coffee: 92 },
  },
  {
    name: "Bosnia and Herzegovina",
    code: "ba",
    flag: "https://flagpedia.net/data/flags/w80/ba.png",
    rankings: { Population: 135, FIFA: 74, Size: 129, Crime: 55, GDP: 105, Tourism: 96, Gas: 105, Coffee: 93 },
  },
  {
    name: "Mongolia",
    code: "mn",
    flag: "https://flagpedia.net/data/flags/w80/mn.png",
    rankings: { Population: 136, FIFA: 183, Size: 19, Crime: 53, GDP: 122, Tourism: 107, Gas: 106, Coffee: 94 },
  },
  {
    name: "Armenia",
    code: "am",
    flag: "https://flagpedia.net/data/flags/w80/am.png",
    rankings: { Population: 137, FIFA: 92, Size: 138, Crime: 69, GDP: 132, Tourism: 81, Gas: 107, Coffee: 95 },
  },
  {
    name: "Jamaica",
    code: "jm",
    flag: "https://flagpedia.net/data/flags/w80/jm.png",
    rankings: { Population: 138, FIFA: 53, Size: 160, Crime: 131, GDP: 107, Tourism: 70, Gas: 108, Coffee: 96 },
  },
  {
    name: "Qatar",
    code: "qa",
    flag: "https://flagpedia.net/data/flags/w80/qa.png",
    rankings: { Population: 139, FIFA: 58, Size: 164, Crime: 8, GDP: 42, Tourism: 76, Gas: 109, Coffee: 97 },
  },
  {
    name: "Albania",
    code: "al",
    flag: "https://flagpedia.net/data/flags/w80/al.png",
    rankings: { Population: 140, FIFA: 65, Size: 144, Crime: 89, GDP: 111, Tourism: 72, Gas: 110, Coffee: 98 },
  },
  {
    name: "Puerto Rico",
    code: "pr",
    flag: "https://flagpedia.net/data/flags/w80/pr.png",
    rankings: { Population: 141, FIFA: 174, Size: 169, Crime: 124, GDP: 58, Tourism: 71, Gas: 111, Coffee: 99 },
  },
  {
    name: "Lithuania",
    code: "lt",
    flag: "https://flagpedia.net/data/flags/w80/lt.png",
    rankings: { Population: 142, FIFA: 144, Size: 123, Crime: 30, GDP: 83, Tourism: 82, Gas: 112, Coffee: 100 },
  },
  {
    name: "Namibia",
    code: "na",
    flag: "https://flagpedia.net/data/flags/w80/na.png",
    rankings: { Population: 143, FIFA: 115, Size: 34, Crime: 119, GDP: 129, Tourism: 108, Gas: 113, Coffee: 101 },
  },
  {
    name: "Gambia",
    code: "gm",
    flag: "https://flagpedia.net/data/flags/w80/gm.png",
    rankings: { Population: 144, FIFA: 125, Size: 159, Crime: 83, GDP: 173, Tourism: 141, Gas: 114, Coffee: 102 },
  },
  {
    name: "Botswana",
    code: "bw",
    flag: "https://flagpedia.net/data/flags/w80/bw.png",
    rankings: { Population: 145, FIFA: 140, Size: 48, Crime: 65, GDP: 94, Tourism: 110, Gas: 115, Coffee: 103 },
  },
  {
    name: "Gabon",
    code: "ga",
    flag: "https://flagpedia.net/data/flags/w80/ga.png",
    rankings: { Population: 146, FIFA: 84, Size: 77, Crime: 120, GDP: 70, Tourism: 135, Gas: 116, Coffee: 104 },
  },
  {
    name: "Lesotho",
    code: "ls",
    flag: "https://flagpedia.net/data/flags/w80/ls.png",
    rankings: { Population: 147, FIFA: 125, Size: 141, Crime: 122, GDP: 157, Tourism: 147, Gas: 117, Coffee: 105 },
  },
  {
    name: "North Macedonia",
    code: "mk",
    flag: "https://flagpedia.net/data/flags/w80/mk.png",
    rankings: { Population: 148, FIFA: 67, Size: 148, Crime: 67, GDP: 109, Tourism: 97, Gas: 118, Coffee: 106 },
  },
  {
    name: "Slovenia",
    code: "si",
    flag: "https://flagpedia.net/data/flags/w80/si.png",
    rankings: { Population: 149, FIFA: 57, Size: 152, Crime: 10, GDP: 45, Tourism: 75, Gas: 119, Coffee: 107 },
  },
  {
    name: "Guinea-Bissau",
    code: "gw",
    flag: "https://flagpedia.net/data/flags/w80/gw.png",
    rankings: { Population: 150, FIFA: 125, Size: 133, Crime: 90, GDP: 169, Tourism: 179, Gas: 120, Coffee: 108 },
  },
  {
    name: "Latvia",
    code: "lv",
    flag: "https://flagpedia.net/data/flags/w80/lv.png",
    rankings: { Population: 151, FIFA: 130, Size: 124, Crime: 40, GDP: 84, Tourism: 93, Gas: 121, Coffee: 109 },
  },
  {
    name: "Bahrain",
    code: "bh",
    flag: "https://flagpedia.net/data/flags/w80/bh.png",
    rankings: { Population: 152, FIFA: 86, Size: 185, Crime: 41, GDP: 49, Tourism: 94, Gas: 122, Coffee: 110 },
  },
  {
    name: "Equatorial Guinea",
    code: "gq",
    flag: "https://flagpedia.net/data/flags/w80/gq.png",
    rankings: { Population: 153, FIFA: 88, Size: 145, Crime: 158, GDP: 88, Tourism: 170, Gas: 123, Coffee: 111 },
  },
  {
    name: "Trinidad and Tobago",
    code: "tt",
    flag: "https://flagpedia.net/data/flags/w80/tt.png",
    rankings: { Population: 154, FIFA: 105, Size: 165, Crime: 125, GDP: 79, Tourism: 98, Gas: 124, Coffee: 113 },
  },
  {
    name: "Estonia",
    code: "ee",
    flag: "https://flagpedia.net/data/flags/w80/ee.png",
    rankings: { Population: 155, FIFA: 124, Size: 132, Crime: 41, GDP: 44, Tourism: 100, Gas: 125, Coffee: 114 },
  },
  {
    name: "Mauritius",
    code: "mu",
    flag: "https://flagpedia.net/data/flags/w80/mu.png",
    rankings: { Population: 156, FIFA: 180, Size: 170, Crime: 24, GDP: 102, Tourism: 101, Gas: 126, Coffee: 115 },
  },
  {
    name: "Cyprus",
    code: "cy",
    flag: "https://flagpedia.net/data/flags/w80/cy.png",
    rankings: { Population: 157, FIFA: 125, Size: 171, Crime: 43, GDP: 97, Tourism: 102, Gas: 127, Coffee: 116 },
  },
  {
    name: "Eswatini",
    code: "sz",
    flag: "https://flagpedia.net/data/flags/w80/sz.png",
    rankings: { Population: 158, FIFA: 147, Size: 158, Crime: 117, GDP: 148, Tourism: 137, Gas: 128, Coffee: 117 },
  },
  {
    name: "Djibouti",
    code: "dj",
    flag: "https://flagpedia.net/data/flags/w80/dj.png",
    rankings: { Population: 159, FIFA: 188, Size: 150, Crime: 100, GDP: 164, Tourism: 168, Gas: 129, Coffee: 118 },
  },
  {
    name: "Fiji",
    code: "fj",
    flag: "https://flagpedia.net/data/flags/w80/fj.png",
    rankings: { Population: 160, FIFA: 160, Size: 156, Crime: 62, GDP: 127, Tourism: 103, Gas: 130, Coffee: 119 },
  },
  {
    name: "Réunion",
    code: "re",
    flag: "https://flagpedia.net/data/flags/w80/re.png",
    rankings: { Population: 161, FIFA: 193, Size: 172, Crime: 66, GDP: 98, Tourism: 112, Gas: 131, Coffee: 120 },
  },
  {
    name: "Comoros",
    code: "km",
    flag: "https://flagpedia.net/data/flags/w80/km.png",
    rankings: { Population: 162, FIFA: 125, Size: 174, Crime: 101, GDP: 170, Tourism: 163, Gas: 132, Coffee: 121 },
  },
  {
    name: "Guyana",
    code: "gy",
    flag: "https://flagpedia.net/data/flags/w80/gy.png",
    rankings: { Population: 163, FIFA: 175, Size: 85, Crime: 128, GDP: 99, Tourism: 113, Gas: 133, Coffee: 122 },
  },
  {
    name: "Bhutan",
    code: "bt",
    flag: "https://flagpedia.net/data/flags/w80/bt.png",
    rankings: { Population: 164, FIFA: 183, Size: 134, Crime: 63, GDP: 165, Tourism: 117, Gas: 134, Coffee: 123 },
  },
  {
    name: "Solomon Islands",
    code: "sb",
    flag: "https://flagpedia.net/data/flags/w80/sb.png",
    rankings: { Population: 165, FIFA: 141, Size: 142, Crime: 80, GDP: 176, Tourism: 149, Gas: 135, Coffee: 124 },
  },
  {
    name: "Macao",
    code: "mo",
    flag: "https://flagpedia.net/data/flags/w80/mo.png",
    rankings: { Population: 166, FIFA: 193, Size: 193, Crime: 1, GDP: 40, Tourism: 115, Gas: 136, Coffee: 126 },
  },
  {
    name: "Luxembourg",
    code: "lu",
    flag: "https://flagpedia.net/data/flags/w80/lu.png",
    rankings: { Population: 167, FIFA: 95, Size: 179, Crime: 14, GDP: 35, Tourism: 118, Gas: 137, Coffee: 127 },
  },
  {
    name: "Montenegro",
    code: "me",
    flag: "https://flagpedia.net/data/flags/w80/me.png",
    rankings: { Population: 168, FIFA: 49, Size: 161, Crime: 81, GDP: 133, Tourism: 119, Gas: 138, Coffee: 128 },
  },
  {
    name: "Western Sahara",
    code: "eh",
    flag: "https://flagpedia.net/data/flags/w80/eh.png",
    rankings: { Population: 169, FIFA: 193, Size: 78, Crime: 193, GDP: 193, Tourism: 193, Gas: 139, Coffee: 129 },
  },
  {
    name: "Suriname",
    code: "sr",
    flag: "https://flagpedia.net/data/flags/w80/sr.png",
    rankings: { Population: 170, FIFA: 139, Size: 91, Crime: 112, GDP: 116, Tourism: 120, Gas: 140, Coffee: 130 },
  },
  {
    name: "Cape Verde",
    code: "cv",
    flag: "https://flagpedia.net/data/flags/w80/cv.png",
    rankings: { Population: 171, FIFA: 73, Size: 175, Crime: 98, GDP: 155, Tourism: 122, Gas: 141, Coffee: 131 },
  },
  {
    name: "Micronesia",
    code: "fm",
    flag: "https://flagpedia.net/data/flags/w80/fm.png",
    rankings: { Population: 172, FIFA: 193, Size: 177, Crime: 99, GDP: 183, Tourism: 150, Gas: 142, Coffee: 132 },
  },
  {
    name: "Malta",
    code: "mt",
    flag: "https://flagpedia.net/data/flags/w80/mt.png",
    rankings: { Population: 173, FIFA: 171, Size: 191, Crime: 45, GDP: 92, Tourism: 123, Gas: 143, Coffee: 133 },
  },
  {
    name: "Brunei",
    code: "bn",
    flag: "https://flagpedia.net/data/flags/w80/bn.png",
    rankings: { Population: 174, FIFA: 183, Size: 173, Crime: 16, GDP: 73, Tourism: 126, Gas: 144, Coffee: 135 },
  },
  {
    name: "Belize",
    code: "bz",
    flag: "https://flagpedia.net/data/flags/w80/bz.png",
    rankings: { Population: 175, FIFA: 162, Size: 147, Crime: 136, GDP: 156, Tourism: 127, Gas: 146, Coffee: 136 },
  },
  {
    name: "Bahamas",
    code: "bs",
    flag: "https://flagpedia.net/data/flags/w80/bs.png",
    rankings: { Population: 176, FIFA: 193, Size: 162, Crime: 139, GDP: 100, Tourism: 129, Gas: 147, Coffee: 137 },
  },
  {
    name: "Iceland",
    code: "is",
    flag: "https://flagpedia.net/data/flags/w80/is.png",
    rankings: { Population: 177, FIFA: 72, Size: 106, Crime: 8, GDP: 74, Tourism: 131, Gas: 148, Coffee: 138 },
  },
  {
    name: "Vanuatu",
    code: "vu",
    flag: "https://flagpedia.net/data/flags/w80/vu.png",
    rankings: { Population: 178, FIFA: 164, Size: 163, Crime: 94, GDP: 177, Tourism: 132, Gas: 149, Coffee: 140 },
  },
  {
    name: "Barbados",
    code: "bb",
    flag: "https://flagpedia.net/data/flags/w80/bb.png",
    rankings: { Population: 179, FIFA: 163, Size: 184, Crime: 47, GDP: 114, Tourism: 133, Gas: 150, Coffee: 141 },
  },
  {
    name: "Sao Tome and Principe",
    code: "st",
    flag: "https://flagpedia.net/data/flags/w80/st.png",
    rankings: { Population: 180, FIFA: 193, Size: 176, Crime: 149, GDP: 174, Tourism: 151, Gas: 151, Coffee: 142 },
  },
  {
    name: "Samoa",
    code: "ws",
    flag: "https://flagpedia.net/data/flags/w80/ws.png",
    rankings: { Population: 181, FIFA: 193, Size: 168, Crime: 73, GDP: 160, Tourism: 152, Gas: 152, Coffee: 143 },
  },
  {
    name: "Saint Lucia",
    code: "lc",
    flag: "https://flagpedia.net/data/flags/w80/lc.png",
    rankings: { Population: 182, FIFA: 193, Size: 180, Crime: 138, GDP: 150, Tourism: 153, Gas: 153, Coffee: 144 },
  },
  {
    name: "Kiribati",
    code: "ki",
    flag: "https://flagpedia.net/data/flags/w80/ki.png",
    rankings: { Population: 183, FIFA: 193, Size: 181, Crime: 150, GDP: 181, Tourism: 157, Gas: 154, Coffee: 146 },
  },
  {
    name: "Grenada",
    code: "gd",
    flag: "https://flagpedia.net/data/flags/w80/gd.png",
    rankings: { Population: 184, FIFA: 193, Size: 186, Crime: 151, GDP: 151, Tourism: 159, Gas: 155, Coffee: 147 },
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "vc",
    flag: "https://flagpedia.net/data/flags/w80/vc.png",
    rankings: { Population: 185, FIFA: 193, Size: 187, Crime: 152, GDP: 152, Tourism: 161, Gas: 156, Coffee: 148 },
  },
  {
    name: "Tonga",
    code: "to",
    flag: "https://flagpedia.net/data/flags/w80/to.png",
    rankings: { Population: 186, FIFA: 193, Size: 182, Crime: 153, GDP: 153, Tourism: 164, Gas: 157, Coffee: 149 },
  },
  {
    name: "Antigua and Barbuda",
    code: "ag",
    flag: "https://flagpedia.net/data/flags/w80/ag.png",
    rankings: { Population: 187, FIFA: 193, Size: 183, Crime: 154, GDP: 154, Tourism: 166, Gas: 158, Coffee: 150 },
  },
  {
    name: "Seychelles",
    code: "sc",
    flag: "https://flagpedia.net/data/flags/w80/sc.png",
    rankings: { Population: 188, FIFA: 193, Size: 188, Crime: 155, GDP: 155, Tourism: 169, Gas: 159, Coffee: 151 },
  },
  {
    name: "Andorra",
    code: "ad",
    flag: "https://flagpedia.net/data/flags/w80/ad.png",
    rankings: { Population: 189, FIFA: 193, Size: 189, Crime: 156, GDP: 156, Tourism: 172, Gas: 160, Coffee: 152 },
  },
  {
    name: "Dominica",
    code: "dm",
    flag: "https://flagpedia.net/data/flags/w80/dm.png",
    rankings: { Population: 190, FIFA: 193, Size: 190, Crime: 157, GDP: 157, Tourism: 173, Gas: 161, Coffee: 153 },
  },
  {
    name: "Marshall Islands",
    code: "mh",
    flag: "https://flagpedia.net/data/flags/w80/mh.png",
    rankings: { Population: 191, FIFA: 193, Size: 192, Crime: 158, GDP: 158, Tourism: 176, Gas: 163, Coffee: 154 },
  },
  {
    name: "Saint Kitts and Nevis",
    code: "kn",
    flag: "https://flagpedia.net/data/flags/w80/kn.png",
    rankings: { Population: 192, FIFA: 193, Size: 193, Crime: 159, GDP: 159, Tourism: 177, Gas: 164, Coffee: 159 },
  },
  {
    name: "Liechtenstein",
    code: "li",
    flag: "https://flagpedia.net/data/flags/w80/li.png",
    rankings: { Population: 193, FIFA: 193, Size: 194, Crime: 160, GDP: 160, Tourism: 178, Gas: 165, Coffee: 160 },
  },
]

// Helper function to get random countries for a session
export function getRandomCountries(count = 8): CountryData[] {
  const shuffled = [...countries].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}

// Helper function to generate shuffle flags for animation
export function generateShuffleFlags(targetCountry: CountryData, allCountries: CountryData[]): string[] {
  const otherFlags = allCountries
    .filter((c) => c.name !== targetCountry.name)
    .map((c) => c.flag)
    .sort(() => 0.5 - Math.random())
    .slice(0, 9)

  return [...otherFlags, targetCountry.flag]
}
