// A large array of short, actionable, and easy-to-understand 'Did You Know' facts for GeoHunter
// Each fact should help players get better at the game

export const didYouKnowFacts: string[] = [
  "China is #1 in population but not in FIFA—big population ≠ football power.",
  "Brazil is #1 in coffee and top in FIFA—coffee and football go together here!",
  "Finland is very safe and loves coffee—small, safe countries can surprise you.",
  "USA is #1 in GDP and gas, but not in crime safety—wealth ≠ safety.",
  "France is #1 in tourism but low in coffee—tourists love France, not for coffee!",
  "Russia is the largest country but not top in GDP—size ≠ wealth.",
  "Singapore is tiny but very safe—small can be mighty.",
  "Norway is rich in gas but small in population—resources boost small nations.",
  "Japan is high in GDP, but not top in FIFA—tech > sports here.",
  "India is #1 in population but moderate in GDP—population ≠ individual wealth.",
  "Australia is huge in size but not in population—big land, few people.",
  "Switzerland is small but wealthy—quality over quantity in Europe.",
  "Saudi Arabia is top in gas due to oil—Middle East = energy power.",
  "Thailand is top in tourism—Southeast Asia is a travel hotspot.",
  "Ethiopia is a coffee powerhouse despite low GDP—origin matters in agriculture.",
  "Germany is strong in GDP and FIFA—some countries excel in both economy and sports.",
  "Argentina is a football powerhouse but not in GDP—sports ≠ wealth.",
  "Canada is 2nd in size but low in population—vast lands, few people.",
  "Mexico is high in FIFA and tourism—think football and travel.",
  "Egypt is the most populous Arab country but not top in GDP—population ≠ wealth.",
  "Italy is famous for tourism and football—some countries are good at both.",
  "UK is high in GDP and FIFA—old powers often rank high in both.",
  "Spain is top in tourism and football—Mediterranean countries excel here.",
  "South Korea is strong in GDP and tech but not in FIFA—tech > sports.",
  "Netherlands is safe and wealthy—northern Europe is often both.",
  "Sweden is safe and wealthy—look for patterns in Scandinavia.",
  "Colombia is top in coffee but not in GDP—agriculture ≠ wealth.",
  "Vietnam is rising in coffee but not in GDP—watch for up-and-comers.",
  "Turkey bridges Europe and Asia—location can mean diversity in rankings.",
  "Indonesia is the largest island country but not top in GDP—size ≠ wealth.",
  "Poland is strong in FIFA in Europe—Eastern Europe can surprise you.",
  "Portugal is famous for tourism and football—small countries can excel.",
  "Greece is a top tourist spot but not in GDP—tourism ≠ wealth.",
  "Morocco is top in tourism in Africa—North Africa is a travel hub.",
  "South Africa is high in GDP in Africa but not in population—wealth ≠ size.",
  "Nigeria is Africa's most populous country but not top in GDP—population ≠ wealth.",
  "Kenya is famous for coffee and safaris—look for unique strengths.",
  "Tunisia is a top tourist spot in Africa—small countries can lead in tourism.",
  "Malaysia is high in tourism and GDP in Asia—Southeast Asia is diverse.",
  "Singapore is the safest in Asia but not in size—safety ≠ size.",
  "Philippines is an island nation with many tourists—archipelagos attract visitors.",
  "Brazil is #1 in FIFA in South America—football is king here.",
  "Argentina is #2 in FIFA in South America—close rivals matter.",
  "Chile is high in safety in South America—look for outliers.",
  "Peru is famous for tourism (Machu Picchu) but not in GDP—tourism ≠ wealth.",
  "Colombia is high in coffee and tourism—some countries have multiple strengths.",
  "Uruguay is safe and good in football—small countries can be strong.",
  "Paraguay is landlocked in South America—location affects rankings.",
  "Bolivia is high in altitude but not in GDP—geography ≠ wealth.",
  "Ecuador is on the equator but not top in GDP—location ≠ wealth.",
  "Venezuela is rich in oil but not in safety—resources ≠ safety.",
  "Guatemala is a top coffee producer but not in GDP—agriculture ≠ wealth.",
  "Costa Rica is famous for eco-tourism and peace—unique policies can matter.",
  "Panama is known for its canal but not in GDP—famous ≠ wealthy.",
  "Jamaica is famous for tourism and music—culture can boost tourism.",
  "Cuba is an island nation but not top in tourism—politics can affect rankings.",
  "Dominican Republic is top in Caribbean tourism—look for regional leaders.",
  "Haiti shares an island with the Dominican Republic but ranks lower—neighbors can differ a lot.",
  "Bahamas is a top tourist spot in the Caribbean—small islands can lead in tourism.",
  "Barbados is a small island nation—size doesn't limit tourism.",
  "Trinidad and Tobago is famous for music but not in GDP—culture ≠ wealth.",
  "Antigua and Barbuda is a small island nation—small can be mighty in tourism.",
  "St. Kitts and Nevis is the smallest country in the Americas—smallest ≠ weakest.",
  "Grenada is known as the Spice Island—unique exports can matter.",
  "St. Vincent and the Grenadines is a small island nation—look for hidden gems.",
  "St. Lucia is famous for tourism—Caribbean islands often lead in travel.",
  "Dominica is called the Nature Island—nature can attract tourists.",
  "El Salvador is the smallest country in Central America—small ≠ weak.",
  "Honduras is famous for coffee but not in GDP—exports ≠ wealth.",
  "Nicaragua is the largest country in Central America but not in GDP—size ≠ wealth.",
  "Costa Rica is known for peace (no army) and tourism—policies can affect rankings.",
  "Panama connects North and South America—location can be strategic.",
  "Argentina is famous for tango and beef—culture can be a strength.",
  "Brazil is famous for the Amazon rainforest—nature ≠ wealth.",
  "Chile is the longest country north-south—unique shapes can mean unique rankings.",
  "Peru is home to the Andes mountains—mountains ≠ wealth.",
  "Colombia is the only South American country with coasts on both oceans—geography can be an advantage.",
  "Venezuela has the world's highest waterfall (Angel Falls)—nature ≠ wealth.",
  "Guyana is the only English-speaking country in South America—language can set countries apart.",
  "Suriname is the smallest country in South America—small ≠ weak.",
  "Ecuador uses the US dollar as currency—currency choice can be unique.",
  "Bolivia has two capitals—history can affect rankings.",
  "Paraguay is one of two landlocked countries in South America—landlocked ≠ isolated.",
  "Uruguay is the least corrupt country in South America—governance can matter.",
  "Brazil has the most World Cup wins—football is a national strength.",
  "Argentina won the World Cup in 2022—recent wins can boost rankings.",
  "Germany has won the World Cup four times—Europe is strong in football.",
  "Italy has won the World Cup four times—tradition matters in sports.",
  "France won the World Cup in 2018—recent champions can be top ranked.",
  "Spain won the World Cup in 2010—look for recent winners.",
  "England won the World Cup in 1966—history can matter in rankings.",
  "Uruguay won the first World Cup in 1930—firsts can be important.",
  "Russia spans Europe and Asia—transcontinental countries can have mixed rankings.",
  "Turkey is in both Europe and Asia—location can mean diversity.",
  "Egypt is in both Africa and Asia—look for unique locations.",
  "Kazakhstan is the largest landlocked country—landlocked ≠ small.",
  "Mongolia is the least densely populated country—space ≠ population.",
  "Saudi Arabia is the largest country in the Middle East—size can mean resources.",
  "Israel is a leader in technology but not in size—tech ≠ size.",
  "UAE is famous for skyscrapers and tourism—modernization can boost rankings.",
  "Qatar is the richest country per person—small ≠ poor.",
  "Oman is known for peace and safety—policies can affect rankings.",
  "Jordan is famous for Petra—history can attract tourists.",
  "Lebanon is famous for food and history—culture can be a strength.",
  "Syria is one of the oldest countries—age ≠ wealth.",
  "Iraq is the birthplace of writing—history ≠ current wealth.",
  "Iran is famous for Persian culture—culture can be a strength.",
  "Pakistan is the 5th most populous country—population ≠ GDP.",
  "Bangladesh is very densely populated—density ≠ wealth.",
  "Sri Lanka is an island nation in South Asia—look for unique locations.",
  "Nepal is home to Mount Everest—mountains ≠ wealth.",
  "Bhutan measures happiness, not GDP—different priorities can affect rankings.",
  "Maldives is the lowest country by elevation—geography can be unique.",
  "Indonesia has the most islands—archipelagos can be diverse.",
  "Philippines has over 7,000 islands—more islands ≠ more wealth.",
  "Thailand is the only Southeast Asian country never colonized—history can affect rankings.",
  "Vietnam is famous for coffee and rice—exports can be a strength.",
  "Malaysia is famous for diversity—diversity can boost rankings.",
  "Singapore is a city and a country—city-states can be unique.",
  "Brunei is rich in oil—resources can boost small countries.",
  "Cambodia is famous for Angkor Wat—history can attract tourists.",
  "Laos is the only landlocked country in Southeast Asia—landlocked ≠ isolated.",
  "Myanmar is also called Burma—names can change, rankings too.",
  "Timor-Leste is the newest country in Asia—new countries can have unique rankings.",
  "Australia is both a country and a continent—unique status can mean unique rankings.",
  "New Zealand is famous for rugby and nature—sports and nature can be strengths.",
  "Fiji is a top tourist spot in the Pacific—small islands can lead in tourism.",
  "Papua New Guinea is very diverse in languages—diversity can be a strength.",
  "Solomon Islands is made up of many islands—archipelagos can be unique.",
  "Vanuatu is a Pacific island nation—small ≠ weak.",
  "Samoa is famous for rugby—sports can be a national strength.",
  "Tonga is a Pacific kingdom—monarchies can be unique.",
  "Tuvalu is one of the smallest countries—small ≠ unimportant.",
  "Kiribati is in all four hemispheres—location can be unique.",
  "Marshall Islands is famous for atolls—geography can be a strength.",
  "Nauru is the least visited country—small ≠ unimportant.",
  "Palau is famous for diving—nature can attract tourists.",
  "Monaco is the most densely populated country—density ≠ size.",
  "Vatican City is the smallest country—small ≠ weak.",
  "San Marino is one of the oldest republics—age ≠ size.",
  "Liechtenstein is a tiny, wealthy country—small ≠ poor.",
  "Andorra is in the Pyrenees mountains—location can be unique.",
  "Luxembourg is very rich—small countries can be wealthy.",
  "Malta is an island in the Mediterranean—location can boost tourism.",
  "Iceland is famous for volcanoes and safety—nature and safety can go together.",
  "Greenland is the largest island—size ≠ population.",
  "Faroe Islands are part of Denmark—territories can have unique rankings.",
  "Åland Islands are part of Finland—autonomy can affect rankings.",
  "Czechia is also called the Czech Republic—names can change, rankings too.",
  "Slovakia split from Czechia in 1993—history can affect rankings.",
  "Hungary is famous for the Danube river—rivers can be a strength.",
  "Romania is home to the Carpathian mountains—mountains ≠ wealth.",
  "Bulgaria is the oldest country in Europe—age ≠ wealth.",
  "Serbia is landlocked in the Balkans—landlocked ≠ isolated.",
  "Croatia is famous for its coastline—coasts can boost tourism.",
  "Slovenia is small but very green—nature can be a strength.",
  "Montenegro means 'Black Mountain'—names can hint at geography.",
  "Albania is on the Adriatic Sea—location can boost tourism.",
  "North Macedonia is landlocked in the Balkans—landlocked ≠ isolated.",
  "Greece is the birthplace of democracy—history can be a strength.",
  "Cyprus is an island in the Mediterranean—location can boost tourism.",
  "Turkey is in both Europe and Asia—location can mean diversity.",
  "Russia is the largest country in both Europe and Asia—size can mean diversity in rankings.",
  "🇳🇴 Norway is rich in gas (#15) but small in population (#119)—natural resources boost small nations.",
  "🇦🇷 Argentina is #3 in beef exports but #25 in GDP—exports ≠ overall wealth.",
  "🇨🇭 Switzerland is #20 in GDP but #98 in population—small, rich countries can surprise you.",
  "🇸🇬 Singapore is #2 in safety but #190 in size—tiny can be mighty.",
  "🇳🇱 Netherlands is #5 in exports but #69 in population—trade can boost small countries.",
  "🇸🇦 Saudi Arabia is #7 in gas but #41 in population—energy powers the economy.",
  "🇨🇦 Canada is #2 in size but #38 in population—big land, few people.",
  "🇧🇪 Belgium is #13 in exports but #81 in population—small countries can be trade giants.",
  "🇦🇺 Australia is #6 in size but #55 in population—vast lands, not always crowded.",
  "🇫🇮 Finland is #3 in safety but #116 in population—safe places can be small.",
  "🇮🇱 Israel is #8 in tech but #100 in population—innovation ≠ size.",
  "🇰🇷 South Korea is #10 in GDP but #28 in population—tech boosts the economy.",
  "🇲🇾 Malaysia is #12 in tourism but #45 in population—tourism can be a big deal for mid-sized countries.",
  "🇵🇱 Poland is #19 in FIFA but #38 in GDP—football ≠ economy.",
  "🇹🇷 Turkey is #17 in tourism but #19 in population—some countries are balanced in many ways.",
  "🇦🇹 Austria is #11 in safety but #97 in population—Europe has many safe, small countries.",
  "🇨🇱 Chile is #7 in safety but #62 in population—look for safe spots in South America.",
  "🇵🇹 Portugal is #12 in tourism but #89 in population—tourism can outshine size.",
  "🇬🇷 Greece is #13 in tourism but #87 in population—history attracts visitors.",
  "🇹🇭 Thailand is #10 in tourism but #20 in population—tourism can be a top strength.",
  "🇪🇬 Egypt is #14 in population but #51 in GDP—big population, not always big economy.",
  "🇳🇬 Nigeria is #7 in population but #27 in GDP—Africa's giant, but not in wealth.",
  "🇻🇳 Vietnam is #2 in coffee but #37 in GDP—exports can be a specialty.",
  "🇨🇴 Colombia is #3 in coffee but #42 in GDP—look for export leaders.",
  "🇪🇹 Ethiopia is #5 in coffee but #70 in GDP—origin matters in agriculture.",
  "🇵🇪 Peru is #6 in tourism but #49 in GDP—tourism can be a main draw.",
  "🇲🇦 Morocco is #9 in tourism but #60 in GDP—North Africa is a travel hub.",
  "🇦🇪 UAE is #8 in GDP per capita but #93 in population—wealth ≠ size.",
  "🇶🇦 Qatar is #1 in GDP per capita but #139 in population—small, super-rich.",
  "🇧🇭 Bahrain is #23 in GDP per capita but #152 in population—tiny, wealthy nations exist.",
  "🇰🇼 Kuwait is #4 in GDP per capita but #129 in population—oil can make a country rich.",
  "🇱🇺 Luxembourg is #2 in GDP per capita but #167 in population—Europe has tiny, rich countries.",
  "🇲🇹 Malta is #10 in tourism but #171 in population—small islands can be big in travel.",
  "🇮🇸 Iceland is #1 in safety but #180 in population—safe, small, and unique.",
  "🇲🇨 Monaco is #1 in density but #195 in population—tiny ≠ unimportant.",
  "🇻🇦 Vatican City is #1 in smallness—smallest can be special.",
  // ... more facts in this style ...
]; 