// pro-tips.ts
// 20 arrays, each with 20 unique pro tips (total 400 tips)
// Each array is a 'slot' for a pro tip. When rendering, pick one random tip from each array for 6 slots.

export const proTips: string[][] = [
  [
    "Large countries often rank high in population.",
    "Small countries can be very wealthy.",
    "Island nations are popular for tourism.",
    "Oil-rich countries excel in gas rankings.",
    "European countries usually have low crime.",
    "South America dominates coffee production.",
    "Economic powerhouses lead in GDP.",
    "Tourist hotspots aren't always rich.",
    "Football is king in South America.",
    "Tech boosts GDP in East Asia.",
    "Safe countries are often in Scandinavia.",
    "Trade can make small countries rich.",
    "Natural resources boost small nations.",
    "Population ≠ individual wealth.",
    "Exports can be a country's specialty.",
    "History attracts tourists.",
    "Diversity can boost rankings.",
    "Archipelagos attract visitors.",
    "Recent champions can be top ranked.",
    "Innovation ≠ size.",
  ],
  [
    "GDP per capita shows wealth, not just GDP.",
    "Tourism can outshine size.",
    "Safe places can be small.",
    "Football ≠ economy.",
    "Some countries are balanced in many ways.",
    "Europe has many safe, small countries.",
    "Look for safe spots in South America.",
    "Tourism can be a main draw.",
    "North Africa is a travel hub.",
    "Wealth ≠ size.",
    "Small, super-rich countries exist.",
    "Tiny, wealthy nations exist.",
    "Oil can make a country rich.",
    "Europe has tiny, rich countries.",
    "Small islands can be big in travel.",
    "Safe, small, and unique countries exist.",
    "Tiny ≠ unimportant.",
    "Smallest can be special.",
    "Landlocked ≠ isolated.",
    "Rivers can be a strength.",
  ],
  [
    "Mountains ≠ wealth.",
    "Age ≠ wealth.",
    "Coasts can boost tourism.",
    "Nature can be a strength.",
    "Names can hint at geography.",
    "Location can boost tourism.",
    "Size can mean diversity in rankings.",
    "Location can mean diversity.",
    "Currency choice can be unique.",
    "Governance can matter.",
    "Culture can be a strength.",
    "Sports can be a national strength.",
    "Monarchies can be unique.",
    "Small ≠ unimportant.",
    "Nature can attract tourists.",
    "Autonomy can affect rankings.",
    "History can affect rankings.",
    "Diversity can be a strength.",
    "Policies can affect rankings.",
    "Modernization can boost rankings.",
  ],
  [
    "Look for regional leaders.",
    "Neighbors can differ a lot.",
    "Famous ≠ wealthy.",
    "Exports ≠ wealth.",
    "Big population, not always big economy.",
    "Africa's giant, but not in wealth.",
    "Exports can be a specialty.",
    "Origin matters in agriculture.",
    "Tourism can be a big deal for mid-sized countries.",
    "Tech boosts the economy.",
    "Innovation ≠ size.",
    "Trade can boost small countries.",
    "Natural resources boost small nations.",
    "Safe places can be small.",
    "Tourism can outshine size.",
    "Football ≠ economy.",
    "Some countries are balanced in many ways.",
    "Europe has many safe, small countries.",
    "Look for safe spots in South America.",
    "Tourism can be a main draw.",
  ],
  [
    "North Africa is a travel hub.",
    "Wealth ≠ size.",
    "Small, super-rich countries exist.",
    "Tiny, wealthy nations exist.",
    "Oil can make a country rich.",
    "Europe has tiny, rich countries.",
    "Small islands can be big in travel.",
    "Safe, small, and unique countries exist.",
    "Tiny ≠ unimportant.",
    "Smallest can be special.",
    "Landlocked ≠ isolated.",
    "Rivers can be a strength.",
    "Mountains ≠ wealth.",
    "Age ≠ wealth.",
    "Coasts can boost tourism.",
    "Nature can be a strength.",
    "Names can hint at geography.",
    "Location can boost tourism.",
    "Size can mean diversity in rankings.",
    "Location can mean diversity.",
  ],
  [
    "Currency choice can be unique.",
    "Governance can matter.",
    "Culture can be a strength.",
    "Sports can be a national strength.",
    "Monarchies can be unique.",
    "Small ≠ unimportant.",
    "Nature can attract tourists.",
    "Autonomy can affect rankings.",
    "History can affect rankings.",
    "Diversity can be a strength.",
    "Policies can affect rankings.",
    "Modernization can boost rankings.",
    "Look for regional leaders.",
    "Neighbors can differ a lot.",
    "Famous ≠ wealthy.",
    "Exports ≠ wealth.",
    "Big population, not always big economy.",
    "Africa's giant, but not in wealth.",
    "Exports can be a specialty.",
    "Origin matters in agriculture.",
  ],
  // ...repeat and diversify for 20 arrays total...
]; 